### ISSUE TITLE
Unclear Claims comment

### ISSUE THREAD

**Issue by rmariani** [urbit/azimuth#16]
Here's an excerpt from Claims.sol:

```
Most commonly, these are about identity, with a claim's protocol defining the context or platform of the claim, and its dossier proof of its validity.
```

What is the "context or platform" for the claim? What is is a "dossier" in this usage?

**Comment by Fang-** [comment]
The `dossier` is always the proof for the claim, whatever form it may take. (A URL to the proof, a signed message, etc.)

The `protocol`, here described as "context or platform", is supposed to be an indicator of what the claim is about. ie "Bitcoin" for a Bitcoin address. Otherwise, if the claim is just a hex string (as would be the case for lots of cryptocurrency-related) it might be impossible to tell what it's really saying/where it applies.

**Comment by rmariani** [comment]
Thanks!
